export interface DefaultNewsQuery {
  query: string;
  name: string;
  signal_kind:
    | "funding"
    | "acquisition"
    | "leadership_change"
    | "product_launch"
    | "expansion"
    | "regulation"
    | "churn_risk"
    | "competitor_move"
    | "hiring"
    | "press_mention";
  poll_interval_minutes: number;
  source_tier: "aggregator";
  source_authority: number;
  source_reason: string;
}

export const DEFAULT_GOOGLE_NEWS_QUERIES: DefaultNewsQuery[] = [
  {
    query: "startup funding round Series A B C",
    name: "Funding — Series A–C",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "startup raises seed round",
    name: "Funding — Seed",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "startup raises pre-seed funding",
    name: "Funding — Pre-seed",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "startup closes Series A funding",
    name: "Funding — Closed round",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "startup secures growth funding",
    name: "Funding — Growth",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "AI startup raises funding",
    name: "Funding — AI",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "SaaS company fundraising venture capital",
    name: "Funding — SaaS/VC",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "fintech startup raised million funding",
    name: "Funding — Fintech",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "healthtech startup funding investment",
    name: "Funding — Healthtech",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "cybersecurity startup raises funding",
    name: "Funding — Cybersecurity",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "B2B SaaS startup raises funding",
    name: "Funding — B2B SaaS",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_funding_recall",
  },
  {
    query: "company acquisition deal announced tech",
    name: "Acquisition — Tech",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_ma_recall",
  },
  {
    query: "startup acquired by company",
    name: "Acquisition — Startup",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_ma_recall",
  },
  {
    query: "company to acquire startup",
    name: "Acquisition — To acquire",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_ma_recall",
  },
  {
    query: "fintech acquisition merger",
    name: "Acquisition — Fintech",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_ma_recall",
  },
  {
    query: "health company acquisition announced",
    name: "Acquisition — Healthcare",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_ma_recall",
  },
  {
    query: "company hires new CTO CPO CISO CFO",
    name: "Leadership — C-suite hire",
    signal_kind: "leadership_change",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_leadership_recall",
  },
  {
    query: "company appoints new CEO CFO CTO",
    name: "Leadership — Appointment",
    signal_kind: "leadership_change",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_leadership_recall",
  },
  {
    query: "startup appoints chief revenue officer",
    name: "Leadership — CRO hire",
    signal_kind: "leadership_change",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_leadership_recall",
  },
  {
    query: "company launches new product platform",
    name: "Product launch",
    signal_kind: "product_launch",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_launch_recall",
  },
  {
    query: "company expansion new market launch",
    name: "Expansion — new market",
    signal_kind: "expansion",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_expansion_recall",
  },
  {
    query: "tech company new office expansion hiring",
    name: "Expansion — office + hiring",
    signal_kind: "expansion",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_expansion_recall",
  },
  {
    query: "\"hiring VP sales\" OR \"hiring head of sales\" OR \"hiring CRO\"",
    name: "Hiring — GTM leadership",
    signal_kind: "hiring",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_hiring_recall",
  },
  {
    query: "\"hiring head of engineering\" OR \"hiring VP engineering\" OR \"hiring CTO\"",
    name: "Hiring — engineering leadership",
    signal_kind: "hiring",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_hiring_recall",
  },
  {
    query: "\"hiring founding engineer\" OR \"hiring founding AE\" OR \"hiring founding designer\"",
    name: "Hiring — founding team",
    signal_kind: "hiring",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_hiring_recall",
  },
  {
    query: "startup hiring RevOps OR \"customer success lead\" OR \"head of growth\"",
    name: "Hiring — RevOps + growth",
    signal_kind: "hiring",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_hiring_recall",
  },
  {
    query: "company enters new market expansion",
    name: "Expansion — market entry",
    signal_kind: "expansion",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_expansion_recall",
  },
  {
    query: "government regulation technology compliance",
    name: "Regulation — tech compliance",
    signal_kind: "regulation",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_regulation_recall",
  },
  {
    query: "financial regulation update SEC FINRA",
    name: "Regulation — SEC / FINRA",
    signal_kind: "regulation",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_regulation_recall",
  },
  {
    query: "healthcare compliance regulation update FDA",
    name: "Regulation — FDA / healthcare",
    signal_kind: "regulation",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_regulation_recall",
  },
  {
    query: "company data breach security incident compliance",
    name: "Pain — data breach",
    signal_kind: "churn_risk",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_pain_recall",
  },
  {
    query: "company issues RFP software vendor",
    name: "Pain — RFP/vendor search",
    signal_kind: "churn_risk",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_pain_recall",
  },
  {
    query: "company faces lawsuit regulatory investigation",
    name: "Pain — investigation",
    signal_kind: "churn_risk",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_pain_recall",
  },
  {
    query: "company selects vendor platform implementation",
    name: "Intent — platform implementation",
    signal_kind: "competitor_move",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_intent_recall",
  },
  {
    query: "company migrates to new platform cloud",
    name: "Pain — cloud migration",
    signal_kind: "churn_risk",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_pain_recall",
  },
  {
    query: "company signs contract digital transformation",
    name: "Intent — digital transformation",
    signal_kind: "competitor_move",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_intent_recall",
  },
  {
    query: "company opens manufacturing facility expansion",
    name: "Expansion — facility opening",
    signal_kind: "expansion",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_expansion_recall",
  },
  {
    query: "company receives government contract technology",
    name: "Intent — government contract",
    signal_kind: "competitor_move",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_intent_recall",
  },
  {
    query: "startup lands enterprise customer contract",
    name: "Intent — enterprise contract",
    signal_kind: "competitor_move",
    poll_interval_minutes: 30,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_intent_recall",
  },
  {
    query: "company fined regulatory compliance",
    name: "Regulation — enforcement",
    signal_kind: "regulation",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_regulation_recall",
  },
  {
    query: "company cuts costs automation initiative",
    name: "Pain — cost cutting",
    signal_kind: "churn_risk",
    poll_interval_minutes: 60,
    source_tier: "aggregator",
    source_authority: 0.66,
    source_reason: "free_pain_recall",
  },
];

export interface DefaultRssFeed {
  url: string;
  name: string;
  signal_kind:
    | "press_mention"
    | "funding"
    | "product_launch"
    | "regulation"
    | "acquisition";
  poll_interval_minutes: number;
  source_tier: "trusted" | "official";
  source_authority: number;
  source_reason: string;
}

export const DEFAULT_RSS_FEEDS: DefaultRssFeed[] = [
  {
    url: "https://techcrunch.com/category/startups/feed/",
    name: "TechCrunch — Startups",
    signal_kind: "press_mention",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.78,
    source_reason: "curated_tech_press",
  },
  {
    url: "https://techcrunch.com/category/enterprise/feed/",
    name: "TechCrunch — Enterprise",
    signal_kind: "press_mention",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.78,
    source_reason: "curated_tech_press",
  },
  {
    url: "https://www.finsmes.com/feed",
    name: "FINsMES",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.7,
    source_reason: "curated_funding_press",
  },
  {
    url: "https://www.eu-startups.com/feed/",
    name: "EU-Startups",
    signal_kind: "press_mention",
    poll_interval_minutes: 60,
    source_tier: "trusted",
    source_authority: 0.72,
    source_reason: "curated_startup_press",
  },
  {
    url: "https://venturebeat.com/category/ai/feed/",
    name: "VentureBeat — AI",
    signal_kind: "press_mention",
    poll_interval_minutes: 60,
    source_tier: "trusted",
    source_authority: 0.75,
    source_reason: "curated_ai_press",
  },
  {
    url: "https://siliconangle.com/feed/",
    name: "SiliconANGLE",
    signal_kind: "press_mention",
    poll_interval_minutes: 60,
    source_tier: "trusted",
    source_authority: 0.72,
    source_reason: "curated_tech_press",
  },
  {
    url: "https://www.securityweek.com/feed/",
    name: "SecurityWeek",
    signal_kind: "press_mention",
    poll_interval_minutes: 60,
    source_tier: "trusted",
    source_authority: 0.76,
    source_reason: "curated_security_press",
  },
  {
    url: "https://feeds.feedburner.com/TheHackersNews",
    name: "The Hacker News",
    signal_kind: "press_mention",
    poll_interval_minutes: 60,
    source_tier: "trusted",
    source_authority: 0.72,
    source_reason: "curated_security_press",
  },
  {
    url: "https://www.sec.gov/news/pressreleases.rss",
    name: "SEC press releases",
    signal_kind: "regulation",
    poll_interval_minutes: 60,
    source_tier: "official",
    source_authority: 0.9,
    source_reason: "official_regulator",
  },
  {
    url: "https://www.prnewswire.com/rss/news-releases-list.rss?category=TEC&language=en",
    name: "PRNewswire — Technology",
    signal_kind: "press_mention",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.8,
    source_reason: "press_release_wire",
  },
  {
    url: "https://www.prnewswire.com/rss/news-releases-list.rss?category=FN&language=en",
    name: "PRNewswire — Financial Services",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.8,
    source_reason: "press_release_wire",
  },
  {
    url: "https://www.prnewswire.com/rss/news-releases-list.rss?category=HTH&language=en",
    name: "PRNewswire — Healthcare",
    signal_kind: "press_mention",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.8,
    source_reason: "press_release_wire",
  },
  {
    url: "https://feed.businesswire.com/rss/home/?rss=G22",
    name: "Business Wire — Technology",
    signal_kind: "press_mention",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.82,
    source_reason: "press_release_wire",
  },
  {
    url: "https://feed.businesswire.com/rss/home/?rss=G17",
    name: "Business Wire — Financial Services",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.82,
    source_reason: "press_release_wire",
  },
  {
    url: "https://www.globenewswire.com/RssFeed/subjectcode/23-Mergers%2Band%2BAcquisitions",
    name: "GlobeNewswire — M&A",
    signal_kind: "acquisition",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.8,
    source_reason: "press_release_wire",
  },
  {
    url: "https://www.globenewswire.com/RssFeed/subjectcode/01-Financing%2BAgreements",
    name: "GlobeNewswire — Financing Agreements",
    signal_kind: "funding",
    poll_interval_minutes: 30,
    source_tier: "trusted",
    source_authority: 0.8,
    source_reason: "press_release_wire",
  },
];
